### PR TITLE
HTTP Content-Disposition header updates filename field in HTTP::Info

### PR DESCRIPTION
**Pull request by albertzaharovits**
ticket: <https://bro-tracker.atlassian.net/projects/BIT/issues/BIT-1493>

### CODE REVIEW

**Comment by rsmmr** [comment]
Hmm ... Not sure this is the right fix. Seth, can you take a look?

**Comment by sethhall** [comment]
Hi Albert.  I think I agree with Robin, this may not be the right fix.  As I look at this code more I'm seeing that my original implementation of it is pretty weak.  It actually needs to turn into orig_filenames and resp_filenames.  

I think that the `filename` field should be removed from `http/main.bro` and the `orig_filenames` and `resp_filenames` fields should be created and filled out either in a script in the policy/ directory or done in the entities.bro file.  I don't have a strong opinion either way.  

Another small note, your patch is only handling the case where a file name is given in a CONTENT-DISPOSITION header, but it's possible to also give a filename in the CONTENT-TYPE header which is the next else if block in that same area you set the file name.

Would you like to make the changes I've mentioned or would you like me to handle them when I'm merging?

**Comment by albertzaharovits** [comment]
Hi,
Indeed there should be `orig_filename` and `resp_filename`. I can make the necessary changes (including the `name` param in CONTENT-TYPE header ... and `title`??).
However I have a question (and I realise this might be another topic): [extract_filename_from_content_disposition](https://github.com/bro/bro/blob/master/scripts/base/utils/files.bro#L20) is very minimal compared to [these tests](http://greenbytes.de/tech/tc2231/) (specifically encoding prefix, and RFC2231 parameter continuation). What's the reason for this?

**Comment by sethhall** [comment]
Thanks for continuing to work on it.

extract_filename_from_content_disposition is minimal because it was only done to parse the types of headers I had seen before.  I believe it should work with parameter continuation because I think the MIME parser deals with that internally.  If you are interested, you could create a test similar to the software version parsing test (https://github.com/bro/bro/blob/master/testing/btest/scripts/base/frameworks/software/version-parsing.bro).  What's there already should be very general and deal with a lot of weird stuff, but I'm sure you'll find cases where it doesn't work if you look hard enough. :)

**Comment by sethhall** [comment]
Albert, any update on this pull request?

**Comment by albertzaharovits** [comment]
Sorry for the delay, expect an update by the end of the week.

**Comment by sethhall** [comment]
No worries.  Thanks!

**Comment by rsmmr** [comment]
Is there any update here?

**Comment by rsmmr** [comment]
As there doesn't seem to be further activity,I'm closing this. Feel free to reopen once there's an update.

**Pull request closed without merging**
