### PR TITLE
fixed gssapi parsing, specifically for parsing out krb

### PR DESCRIPTION
**Pull request by juno0812**
Added oid field to gssapi protocol in order to accurately compare in the analyzer.  Fixed comparisons and logic in gssapi analyzer.

### CODE REVIEW

**Comment by sethhall** [comment]
Can you add a test?  I don't feel comfortable merging this without one.  Thanks!

**Comment by juno0812** [comment]
Of course, I'll add one.  Where in the source tree should a test for this go?  Or do I just attach the files here?  Thanks for your help!

**Comment by 0xxon** [comment]
Patches in Bro are typically trace-file driven and go into testing/btest/...

There are plenty of examples that check parts of the protocol parsers; see https://github.com/bro/bro/blob/master/testing/btest/scripts/base/protocols/krb/kinit.test for an example. Testing is performed using btest, see https://github.com/bro/btest for dails (typically - run tests using btest [path to test-file]; create baseline with btest -u [path to test file].

**Comment by 0xxon** [comment]
Hi,

I just wanted to check if you still are interested in providing tests for this :). If you have more questions on how to best design / create test cases, feel free to drop me an email too.

**Comment by 0xxon** [comment]
Hi,

I am going to close this for the moment. Please feel free to re-open this with tests :). Also - if you have problems creating the testcases, please let either me or @sethhall know - we are happy to help.

**Pull request closed without merging**
