### PR TITLE
Fix GSSAPI handling of Kerberos authenticaiton (with btest support)

### PR DESCRIPTION
**Pull request by jrolli**
This is the same changes proposed in #104, but also provides the proper files to support btest unit testing.

### CODE REVIEW

**Comment by sethhall** [comment]
This change does add the oid which is required, but it breaks NTLMSSP (which is what I've seen most commonly in SMB traffic).  I would love to have this problem fixed, but I think that more work needs to be done on it.

Your change breaks the scripts.base.protocols.smb.smb2 test (which I didn't look into, but I suspect has something to do with NTLMSSP).

You may want to use the wireshark analyzer as a reference for completing this since it appears that they've discovered several edge cases in the real world:
 
https://github.com/wireshark/wireshark/blob/af54b292e60fcdd8d03ec583e2b46c9c51f259a5/epan/dissectors/packet-gssapi.c#L304

**Comment by jrolli** [comment]
Merged refactored code provided by juno0812 which solves the regression for NTLM support in the GSSAPI parser.

**Comment by sethhall** [comment]
Thanks for the changes jolly and juno0812!  From a quick skim this look like something that can be pulled in.  I'm hoping to get to this by the end of the day today.

**Comment by jrolli** [comment]
@sethhall Have you had a chance to do a more thorough review of the changes?  Let me know if you need any additional tests or regression fixes (I didn't notice any) before you can accept it.

**Comment by sethhall** [comment]
Eek,  6 months later isn't great after saying "I'll get to this today".  Does this ticket completely supersede #104?

**Comment by jrolli** [comment]
It does.  #104 was closed because there were no tests (and would have broken another one) so I started this one with the test added.

**Comment by sethhall** [comment]
Thanks for replying so quickly!

**Comment by sethhall** [comment]
Done.  Let me know if you notice any issues with what I committed into master.  I removed a lot of the code you added to the gssapi-analyzer.pac file because it was doing parsing which we try to avoid if possible.  I moved almost all of that parsing into the gssapi-protocol.pac file.

**Pull request merged**
