### PR TITLE
Fixed parsing of V_ASN1_GENERALIZEDTIME timestamps in x509 certificates

### PR DESCRIPTION
**Pull request by yunzheng**
Currently, when a x509 certificate contains a V_ASN1_GENERALIZEDTIME it parses the timestamp incorrectly.

This pull requests fixes the V_ASN1_GENERALIZEDTIME timestamp parsing in x509 certificates.
It also includes a btest case that tests both V_ASN1_GENERALIZEDTIME and V_ASN_UTCTIME pcaps.

### CODE REVIEW

**Comment by yunzheng** [comment]
This is probably a different issue but I noticed that the epoch timestamp is depended on BRO_TZ environment setting.

For example BRO_TZ=UTC is used for running the btest cases, but shouldn't unix/epoch timestamps always be the same as it's timezone independent?

**Comment by 0xxon** [comment]
I refactored your commit a bit in topic/yunzheng/x509-generalizedtime to fit a bit more how the rest of the function does its processing.

Please let me know if you see any issues with the changes.

@rsmmr - could you please merge this?

**Comment by yunzheng** [comment]
0xxon: I don't see any changes though, where can I find it?

**Comment by 0xxon** [comment]
@yunzheng - https://github.com/bro/bro/tree/topic/yunzheng/x509-generalizedtime

**Comment by yunzheng** [comment]
Ah got it, the changes look ok to me

**Pull request merged**
