### PR TITLE
Extend DHCP protocol analyzer with new options.

### PR DESCRIPTION
**Pull request by Mr-Click**
Add the folowing option types:
- 55 Parameters Request List;
- 58 Renewal time;
- 59 Rebinding time;
- 61 Client Identifier;
- 82 Relay Agent Information.

Extend the following events with new parameters, specifically:
- dhcp_discover exports client identifier and parameters request list;
- dhcp_request exports client_identifier and parameters request list;
- dhcp_ack exports rebinding time, renewal time and list of suboptions value of
  dhcp relay agent information option;
- dhcp_inform exports parameters request list.

Add option type specific variables within the scope of DHCP module
(see src/analyzer/protocol/dhcp/types.bif).

Move protocol specific variables "dhcp_msg" and "dhcp_router_list" from scope Global to DHCP::
and adapt inet_net_var in src/NetVar.cc consequently.

Extend src/analyzer/protocols/dhcp/main.bro to handle the new events and to log
dhcp_ack, dhcp_request and dhcp_discover.

Modify scripts/policy/protocols/dhcp/known-devices-and-hostnames.bro to
include new events' variables.

Add .btest scripts for dhck_ack and dhcp_discover messages verifying that new 
options are correctly reported in dhcp.log records.

### CODE REVIEW

**Comment by jsiwek** [comment]
Just adding references back to JIRA issues this may resolve:
https://bro-tracker.atlassian.net/browse/BIT-1630
https://bro-tracker.atlassian.net/browse/BIT-1835

**Comment by rsmmr** [comment]
Almost done, testing and then MR coming

**Comment by sethhall** [comment]
Mr-Click, just wanted to let you know that your changes (and a lot more!) are in branch topic/seth/dhcp-update (https://github.com/bro/bro/tree/topic/seth/dhcp-update)

The base DHCP log is quite different from what it was before, it now represents DHCP "transactions" instead of single DHCP messages.  If you want the fields that you added to the base DHCP log, they can be found in an extension script in policy/protocols/dhcp

I should be done with testing on this branch this week and I'll mark it for a merge request.  Thanks for your changes!

**Comment by Mr-Click** [comment]
@sethhall thanks for the update!!
I'll clone dhcp-update branch to understand what things have changed.

Happy to contribute to the project!

**Comment by sethhall** [comment]
One other thing I forgot to mention is that I don't think this is *quite* working on clusters yet, but I'm hoping to get to that very soon.  I got some stuff in place to start testing that today so I can finish development.

It should work fine with a single process or running on a pcap.

**Comment by sethhall** [comment]
Closing this and moving the discussion and merge request over here: https://bro-tracker.atlassian.net/browse/BIT-1924

**Pull request closed without merging**
