### PR TITLE
Add more parsing to smb2 create request/response.

### PR DESCRIPTION
**Pull request by jwallior**
Same as #98 but also:
- fix and add unit test
- fix memory leak
- move everything in the response/request struct.

### CODE REVIEW

**Comment by sethhall** [comment]
Thanks for the changes! (and sorry for the loooong delay on merging this).  I like that you moved the SMB2 create options into records, it's unfortunate that more of the events didn't end up that way in the first place.

One question though, you said that you fixed a memory leak but I don't see anything in the branch that seems to fix a memory leak.  Did you maybe miss a change somewhere?

One more minor note, we're going to need to fix that test you added soon.  I should have done it already, but I didn't watch closely enough to notice how the diff was done.  That test will be *really* fragile because you're just printing the connection record and as we add and remove scripts going forward, that test will break every time.

**Comment by jsiwek** [comment]
@sethhall the fixed memory leak is in reference to previously closed #98.  i.e. I noticed that PR introduced a memory leak and so I suspect the new changes in this resubmitted PR just never introduced the leak that needed to be fixed in the first place :)

**Comment by sethhall** [comment]
Ah, thanks Jon!

Also, I wanted to point out that I went ahead and made that one test less fragile and pushed it into master.

**Comment by sethhall** [comment]
I don't think it's anything you did, I believe it's a current failure with Bro master on 4.8.

**Pull request merged**
