### PR TITLE
Decrypt the krb ticket if proper keytab is provided. 

### PR DESCRIPTION
**Pull request by jwallior**
We are using this to figure out the user doing SMB2 traffic. Let me know what you think.

### CODE REVIEW

**Comment by 0xxon** [comment]
I think this does indeed look interesting.

However, this does currently make libkrb5 a requirement to build Bro which, I think, is not something that we can/should do. But - I guess one can make this conditional and build it only when libkrb5 is available and otherwise leave the optional empty.

What exactly does authenticationinfo look like when a user is authenticated? Is it possible to create a test-case for that? :)

Also - my Kerberos knowledge is a bit rusty, but:
The keytab file contains your personal keys, right? Does this mean that that only works for tickets granted to the person that created the keytab file on the machine that Bro runs on?

**Comment by jwallior** [comment]
Great. I wanted to make sure you guys were interested before making more changes. 

1. I will add a --with-krb5/--without-krb5 flag to the configure and add #ifdefs such that this requires the user to opt-in.
2. For me (using AD), authenticationinfo is <user>@<domain>. I actually had a unit test, but forgot to push it. This is fixed in my tree (https://github.com/jwallior/bro/tree/krb_changes2). 
3. Let's say you are capturing traffic to a samba file server that is authenticated to AD. When samba authenticates to AD, they both agree on a symmetrical key (that AD will use to encrypt the tickets and that samba will use to decrypt them). This is the key in the keytab file. I can add a help file on how to create the keytab. Once you have this keytab, you can decrypt any ticket that AD generated for that particular samba server. 
One keytab can have multiple keys. So if you have multiple samba servers, you can add all those keys to one keytab and then the traffic hitting any of those servers can be decrypted. 

Hope this help. I will work on adding --with-krb5 and a little help file in the next few days. Assuming this has a good chance of being merged. Let me know if you'd want anything else.

**Comment by 0xxon** [comment]
Give us another day or two to discuss this before you invest significant amounts of time into it :)

**Comment by jwallior** [comment]
Here is how to create keytab: https://wiki.samba.org/index.php/Keytab_Extraction

Regarding optional inclusion, I'm thinking of doing it like LibGeoIP.

**Comment by jwallior** [comment]
Optional krb5 wasn't that hard, so I just did it. On a side note, it requires a change to the cmake submodule. 

Let me know what you think and I'll send a pull request for that one too.

**Comment by losynix** [comment]
@jwallior `#cmakedefine USE_KRB5` should be added in **bro-config.h.in** for the project to build.

**Comment by 0xxon** [comment]
Sorry for the delay on this, I had a bit of a stressy week last week :). I will try to either get this merged this week, or to let you know what else we need.

It would be neat if you would make a pull request for cmake too - or you can let me know where the branch is.

**Comment by 0xxon** [comment]
Thanks :)

**Comment by 0xxon** [comment]
I will commit the merge for this in the next hour or so. it would be nice if you could take a look at it to see if what I did makes sense - I changed around a couple of things, disabled it by default, made initializations static, etc.

**Comment by jwallior** [comment]
Looks reasonable. Thanks. Will pull everything on Monday and run in our environment. Will report any issue.

**Pull request merged**
