### PR TITLE
Add a means of disabling the SMB files log

### PR DESCRIPTION
**Pull request by aeppert**

### CODE REVIEW

**Comment by 0xxon** [comment]
Out of curiosity - what is the advantage of making this an option like this, instead of just calling Log::disable_stream on the log stream?

**Comment by aeppert** [comment]
Typical user, I believe an explicit disable flag is much more clear and it fits with the cmd.log disable flag that already exists. Performance wise, other than an extra file descriptor is there anything I am missing? Perhaps using this flag and disabling the log in bro_init would be the balance of the two options?

**Comment by 0xxon** [comment]
I am not the authority here because that is obviously not my branch - but the cmd_log flag is a bit different, because it is disabled by default, and it allows you to enable another log file (and there is not really a good way to do it that way round).

Otherwise, the default way to disable log files usually is always with Log::disable_stream in local.bro - which is why I was asking. But - that's just my opinion, Seth will know what fits in best with the API design of the smb analyzer.

**Comment by sethhall** [comment]
I don't think I'm going to be merging this for the reason that Johanna pointed out.  The smb_cmd.log is a special case and it was really only intended for development so it has that kind of abnormal mechanism because in nearly all cases, people will want it disabled.  The smb_files.log is intended for operational use however so if people want to disable it, they should be disabling the stream or filtering it heavily.

**Comment by TOoSmOotH** [comment]
Just to throw my $.02 in there people will want to disable the SMB files log. I am running this code in front of a large data center full of MS servers and the data this log generates is mostly duplicated in the normal files.log.

**Comment by aeppert** [comment]
I have to fundamentally disagree. You are assuming all organizations want the same data, Bro is about the data. The expectations would be a simple enable/disable flag for features, nothing more, nothing less. I am not disagreeing with the Log::disable_stream, what I would propose then, is to simply wrap the stream creation in bro_init with the flag to determine if the stream needs to be created at all.

**Comment by aeppert** [comment]
The happy medium here would be to have the MAC portions of SMB files.log added as extensions files.log. Then there isn't a redundant set of logs and streams.

**Comment by sethhall** [comment]
Eventually though, people will want to see things like file deletions happening over SMB (or possibly changing permissions?).  The smb_files.log is meant to also encapsulate actions like that.

I believe that the problem is less about that log and more about the design on that log not yet being complete.  I've already made some changes which should dramatically cut down on the volume of the log and I've been thinking around the problem of how to cut the volume even more while making the resulting data in it more operationally valuable.

I would still recommend disabling the stream if you would like to skip the process of making that log more operationally valuable.

**Pull request closed without merging**
