### PR TITLE
Add smb transaction messages

### PR DESCRIPTION
**Pull request by jbencteux**
Adding and/or exposing SMB1 (also known as CIFS) transaction messages. This improve or add the following SMB messages:

* SMB_COM_TRANSACTION (0x25)
* SMB_COM_TRANSACTION_SECONDARY (0x26)
* SMB_COM_TRANSACTION2 (0x32)
* SMB_COM_TRANSACTION2_SECONDARY (0x33)

It expose an event to the script language if not already done for these messages types. Each of them have more fields exposed than previously (for example the Trans_Data field, which could be seen as the SMB payload). For the ones that are newly added, I respected the  [[MS-CIFS] specification](https://msdn.microsoft.com/en-us/library/ee442092.aspx).

### CODE REVIEW

**Comment by jbencteux** [comment]
I made the changes you suggested in your comment. I also added a test for the smb1_transaction_request event, does it fit your development requirements? I am not quite sure as I never used btest before. If it does, I will put more for the other events.

Also, I found a bug in the way the "setup" field of the transaction message was handled, see commit message for details.

**Comment by jsiwek** [comment]
Thanks, the test you added looks great.  Just let me know when you're done adding others and want me to review again for a final merge.

**Comment by jbencteux** [comment]
I added the missing tests. Could you please do the final review? Thanks

**Comment by jsiwek** [comment]
Thanks for adding the tests and making changes, it's all merged now.

**Pull request merged**
