### PR TITLE
Support 802.11 monitor mode

### PR DESCRIPTION
**Pull request by p-l-**
This patch adds support for Wlan monitor mode capture. It is very tiny since all the work has already been done for RadioTAP header. Also, the patch allows for ARP over Wifi (with and without RadioTAP headers present) analysis.

I've tried to avoid duplicated code.

This is [BIT-1931](https://bro-tracker.atlassian.net/browse/BIT-1931).

### CODE REVIEW

**Comment by sethhall** [comment]
Thanks Pierre!  Could you please include a test for these changes?  If you could at least attach a pcap it would give us the capability to create tests.

Just reach out if you have any questions about making PCAP driven tests.

**Comment by p-l-** [comment]
Thanks @sethhall for your feedback. I have added a test (copied from the RadioTAP test).

**Comment by p-l-** [comment]
@sethhall ... and a couple of tests for ARP in 802.11 (with and without RadioTAP headers).

**Comment by sethhall** [comment]
Merged.  Thanks!

**Comment by p-l-** [comment]
@sethhall they do not pass here either. I don't know if they never passed and I missed that or if they did pass at some point and they no longer for some reason. I'm investigating and will let you know, I'm sorry about that.

**Comment by p-l-** [comment]
@sethhall I have rebased against new master so this PR now only contains the tests to add and a fix for ARP over Wi-Fi.

The tests actually could not work for two reasons: the capture files were incorrect **and** there was a "bug" (see c93b1b4) in ARP parsing.

With the two rebased commits in this PR, the tests now pass for me.

I'm sorry for the waste of time, I should have been more careful...

**Comment by p-l-** [comment]
Erf. I was wrong again. I'll let you know (again) when it is fixed.

**Pull request closed without merging**
