### PR TITLE
DNSSEC support in Bro

### PR DESCRIPTION
**Pull request by fatemabw**
Finally was able to squash the commits into one, and hence requesting a review :)

Thanks,
Fatema.

### CODE REVIEW

**Comment by jsiwek** [comment]
Thanks, just wanted to note that we're soon to release a Bro 2.6-beta w/ an expected 1-2 week code freeze imminent, so it may be a bit before this gets considered for merging into the master branch.

**Comment by fatemabw** [comment]
AH, missed that deadline, no worries.. Thanks! :)

**Comment by jsiwek** [comment]
Thanks for submission, nice job.  The merge is completed on the `dev/2.7` branch and feed back into `master` once the final 2.6 release is done.

I did some noteworthy changes while merging:

* I changed the names of event/record types.  The "addl" and "additional" convention seemed copied from TSIG and not appropriate here.  The reason for TSIG using it is likely that it is supposed to only appear in the "additional" DNS section, but that doesn't apply to all the DNSSEC RR types, some which definitely appear in the "answer" section.
* I reformatted some of the info added to the default `dns.log`.  Idea was to try to add the minimal amount of info there that's still useful.
* I removed the `addl-*.bro` scripts that added extended DNSSEC info to dns.log.  My thinking was that `dns.log` should try to just track the basic info about what records are seen.  Was also thinking it might be better tracked as separate logs, like `dnssec_dnskey.log`, `dnssec_ds.log`, `dnssec_nsec.log`.  Regardless, I think there's a case for minimizing the default scripts that ship with bro as long as it's easy to write similar customization (in this case, it is, one just needs to handle the events and do whatever they want with theinfo).

Let me know if see any problems.

**Comment by fatemabw** [comment]
Hi John,

Thanks for the changes/modification. Makes sense, I had  "addl/additional" as to refer to the additional events and records that can be parsed and recorded by Bro besides the conventional "DNS" RRs, and hence followed the convention of TSIG RR's definition and usage throughout. 

Also, thanks for reformatting and making sense out of the info recorded in dns.log corresponding to DNSSEC RR's. Yeah I wasn't sure what should actually be added to dns.log ans field to signify that an DNSSEC record has been identified in the dns traffic :)

I can make bro-pkg for the addl-*.bro scripts just in case if anyone interested to load them and see what the DNSSEC logs look like. I was also thinking the same that whether it makes sense to record it in a new log file, maybe called as dnssec.log, to record DNSSEC activity over network, and not to load dns.log with it.   Anycase, thanks for taking care of that as well.

One last thing, I have been running this code on production cluster and noticed that since the DNSSEC parsing is enabled, the no. of "dns_unmatched_msg" and "dns_unmatched_reply" in weird.log have increased significantly, hence added "&priority=5" in scripts\base\protocols\dns\main.bro in front of those five DNSSEC events, will see if that helps.  It was a small change and hence didn't request a merge from github, can you add it to the master please, if you think it's fine?

Thanks,
Fatema.

**Comment by fatemabw** [comment]
RE: no. of "dns_unmatched_msg" and "dns_unmatched_reply" in weird.log
 nevermind, I had 
["dns_unmatched_reply"] = ACTION_IGNORE, ["dns_unmatched_msg"] = ACTION_IGNORE,
in base/frameworks/notice/weird.bro previously when I was running Brov2.5.1 before and hence wasn't getting any of those in weird.log, but when I recompiled bro2.5.4 with dnssec support, that setting got overwritten and hence started getting those again.   Sorry for the false alert.

**Comment by jsiwek** [comment]
I still went ahead and added `&priority=5` to the new DNSSEC event handlers if only for the sake of consistency.  Thanks for pointing it out.

**Comment by fatemabw** [comment]
Cool! Thank you.

**Pull request closed without merging**
