### PR TITLE
Add more parsing to smb2 create request/response.

### PR DESCRIPTION
**Pull request by jwallior**

### CODE REVIEW

**Comment by honghuCode** [comment]
Using  bro  cluster 
[manager]
type=manager
host=192.168.38.145
[proxy-1]
type=proxy
host=192.168.38.145
[worker0]
type=worker
host=192.168.38.145
interface=eth1
aux_scripts=/usr/local/bro/etc/local-eth1.bro
[worker1]
type=worker
host=192.168.38.145
interface=eth1
aux_scripts=/usr/local/bro/etc/local-eth1.bro
 when download a executed file ,in the /usr/local/logs/current/files.log , it have two logs about this traffic,why???????  why not only one ?

**Comment by sethhall** [comment]
Vlad?  Are you still planning on taking this on?  I can do it if you don't have time.

**Comment by jwallior** [comment]
Guys -- I'm reworking those patches a bit (unit test are actually failing). I will resubmit the pull request in the next few days. Quick question: the smb2_create_request/response events currently return some of the fields separately instead of 1 big struct. I'm adding more fields and could do a few things:
- add a struct with only the new fields
- or add a new struct and move the old fields in. 
Any preference? (the current pull request should give enough background to what I'm asking).

Also, I'm assuming it's okay to add fields to an event, but if you're worried I'll break people's code, I can make a smb2_create_request_v2() or something. 

Let me know.

**Comment by jsiwek** [comment]
Yeah, I think it's fine to change the signature of the event and break existing code -- we'll likely have other breakages in the next release and have a list of such incompatibilities for people to review in the announcement and NEWS file.

Combining existing + new fields into a single record is probably what I would do here.

Also, while you're changing things, I notice a couple potential memory leaks in the previous commits: when you're creating new RecordVals make sure they actually get consumed.  i.e. allocate them inside just the conditional branch in which they're needed.

**Pull request closed without merging**
